image: Visual Studio 2022

install:
  # g++
  - set PATH=%PATH%;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
  # qmake
  - set QTDIR=C:\Qt\6.8.1\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin
  # Boost
  - set PATH=%PATH%;C:\Libraries\boost_1_63_0
  # SFML (TODO)

build_script:
  # Explore file system
  - echo %cd%
  - dir C:\
  - dir C:\mingw-w64
  - dir C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64
  - dir C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
  - dir C:\cygwin
  - dir C:\cygwin\bin
  - dir C:\Qt
  - dir C:\Qt\6.8.1
  - dir C:\Libraries
  - dir C:\Libraries\boost_1_63_0
  # Find out current folder's content
  - dir
  # magic_enum, download
  - echo "Download magic_enum"
  - cd .. 
  - git clone https://github.com/Neargye/magic_enum
  - cd conquer-chess
  # magic_enum, install
  - echo "Install magic_enum"
  - cd ../magic_enum
  - cmake .
  #- make
  - mingw32-make.exe
  - cd conquer-chess
  # Disservin's chess-library, download
  - echo "Disservin's chess-library"
  - cd ..
  - git clone https://github.com/Disservin/chess-library.git
  - cd conquer-chess
  # Jerrit Gläsker's SFGraphing library
  - echo "Download Jerrit Gläsker's SFGraphing library"
  - cd ..
  - git clone https://github.com/richelbilderbeek/SFGraphing -b patch-1
  - cd conquer-chess
  # Conquer Chess
  - echo "Building Conquer Chess"
  - qmake game.pro
  - mingw32-cd
  #- make release
  - mingw32-make.exe release
  - conquer_chess.exe --version

artifacts:
  # The goal of this CI script
  - path: conquer_chess.exe
