install:
  # g++
  - set PATH=%PATH%;C:\MinGW\bin
  # qmake
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin
  # Boost
  - set PATH=%PATH%;C:\Libraries\boost_1_63_0
  # SFML (TODO)

build_script:
  - echo "Download magic_enum"
  - echo %cd%
  - cd .. 
  - echo %cd%
  - git clone https://github.com/Neargye/magic_enum
  - echo %cd%
  - cd -
  - echo %cd%
  - echo "Install magic_enum"
  - cd ../magic_enum ; cmake . ; make ; cd -
  - echo "Disservin's chess-library"
  - cd .. ; git clone https://github.com/Disservin/chess-library.git ; cd -
  - echo "Download Jerrit Gläsker's SFGraphing library"
  - cd .. ; git clone https://github.com/richelbilderbeek/SFGraphing -b patch-1 ; cd -
  - echo "Building Conquer Chess"
  - qmake game.pro
  - mingw32-cd
  - make release
  - conquer_chess.exe --version

artifacts:
  # The goal of this CI script
  - path: conquer_chess.exe