version: 1.0.{build}
image: Visual Studio 2019

environment:
  matrix:
    - platform: x64

install:
  - choco install sfml -y
  - choco install git -y
  - choco install qt5-sdk -y
  - SET PATH=C:\Qt\5.15.2\mingw81_64\bin;%PATH%
  - cd ..
  - git clone https://github.com/Neargye/magic_enum
  - git clone https://github.com/Disservin/chess-library.git
  - git clone https://github.com/richelbilderbeek/SFGraphing -b patch-1
  - cd conquer_chess

build_script:
  - qmake "DEFINES+=LOGIC_ONLY" game.pro
  - mingw32-make

after_build:
  - mkdir artifacts
  - copy conquer_chess.exe artifacts\conquer_chess.exe

artifacts:
  - path: artifacts\conquer_chess.exe
    name: conquer_chess_windows_exe
