image: Visual Studio 2022

install:
  # g++
  - set PATH=%PATH%;C:\MinGW\bin
  # qmake
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin
  # Boost
  - set PATH=%PATH%;C:\Libraries\boost_1_63_0
  # SFML (TODO)

build_script:
  # Find out path
  - echo %cd%
  - dir C:\
  - dir C:\MinGW
  - dir C:\MinGW\bin
  # Find out current folder's content
  - dir
  # magic_enum, download
  - echo "Download magic_enum"
  - cd .. 
  - git clone https://github.com/Neargye/magic_enum
  - cd conquer-chess
  # magic_enum, install
  - echo "Install magic_enum"
  - cd ../magic_enum
  - cmake .
  - make
  - cd conquer-chess
  # Disservin's chess-library, download
  - echo "Disservin's chess-library"
  - cd ..
  - git clone https://github.com/Disservin/chess-library.git
  - cd conquer-chess
  # Jerrit Gläsker's SFGraphing library
  - echo "Download Jerrit Gläsker's SFGraphing library"
  - cd ..
  - git clone https://github.com/richelbilderbeek/SFGraphing -b patch-1
  - cd conquer-chess
  # Conquer Chess
  - echo "Building Conquer Chess"
  - qmake game.pro
  - mingw32-cd
  - make release
  - conquer_chess.exe --version

artifacts:
  # The goal of this CI script
  - path: conquer_chess.exe
