ignore:
- fonts.* 
- game_view.* 
- game_resources.* 
- loading_screen.* 
- loading_screen_fonts.* 
- loading_screen_songs.* 
- loading_screen_textures.* 
- lobby_view.* 
- main.* 
- menu_view.* 
- options_view.* 
- songs.* 
- textures.* 
