codecov: 
 token: 219d6b99-4761-48dc-a165-a8cf64640356

ignore:
- fonts.cpp 
- fonts.h 
- game_view.cpp 
- game_view.h 
- game_resources.cpp 
- game_resources.h 
- loading_screen.cpp 
- loading_screen.h 
- loading_screen_fonts.cpp 
- loading_screen_fonts.h 
- loading_screen_songs.cpp 
- loading_screen_songs.h 
- loading_screen_textures.cpp 
- loading_screen_textures.h 
- lobby_view.cpp 
- lobby_view.h 
- main.cpp 
- menu_view.cpp 
- menu_view.h 
- options_view.cpp 
- options_view.h 
- songs.cpp 
- songs.h 
- textures.cpp 
- textures 
