# Check that the program can be built
name: Check build

# Check links on the 3rd day of the month.
# 3rd as the first letter of this repo is the 3rd letter in the alphabet.
on:
  push:
    paths:
      - .github/workflows/check_build.yaml
      - "**.cpp"
      - "**.h"
      - "**.pro"
      - "**.pri"
      - "resources/**"
  pull_request:
    paths:
      - .github/workflows/check_build.yaml
      - "**.cpp"
      - "**.h"
      - "**.pro"
      - "**.pri"
      - "resources/**"

jobs:
  check_build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Install SFML
        run: sudo apt install libsfml-dev

      - name: Install Codecov
        run: sudo pip install codecov

      - name: Download magic_enum
        run: |
          cd ..
          git clone https://github.com/Neargye/magic_enum
          cd -

      - name: Install magic_enum
        run: |
          cd ../magic_enum
          cmake .
          make
          cd -

      - name: Download Disservin's chess library
        run: |
          cd ..
          git clone https://github.com/Disservin/chess-library.git
          cd -

      # From https://github.com/jerr-it/SFGraphing
      - name: Download Jerrit Gläsker's SFGraphing library
        run: |
          cd ..
          git clone https://github.com/richelbilderbeek/SFGraphing -b patch-1
          cd -

      - name: qmake
        run: qmake "DEFINES+=LOGIC_ONLY" game.pro

      - name: make
        run: make debug

      - name: run
        run: ./conquer_chess --test

      - name: Measure codecov 1
        run: ./scripts/get_code_cov.sh

      - name: Measure codecov 2
        run: codecov

      - name: Measure codecov 3
        run: bash <(curl -s https://codecov.io/bash)

      - name: play a standard random game
        run: ./conquer_chess --play_standard_random_game

      - name: clean for release build
        run: make clean

      - name: qmake
        run: qmake game.pro

      - name: make
        run: make release --silent
