name: Create website

# Check links on the 3rd day of the month.
# 3rd as the first letter of this repo is the 3rd letter in the alphabet.
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/create_website.yaml
      - "docs/**"
      - mkdocs.yml
  schedule:
    - cron: "0 0 3 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt natsort

      - name: Deploy website
        run: mkdocs gh-deploy --force
